// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BISN_missing
List BISN_missing(arma::mat XDat, arma::uvec row_missing, arma::umat id_missing, double eta, int maxIter, double tol, double r, int s);
RcppExport SEXP _BISNR_BISN_missing(SEXP XDatSEXP, SEXP row_missingSEXP, SEXP id_missingSEXP, SEXP etaSEXP, SEXP maxIterSEXP, SEXP tolSEXP, SEXP rSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XDat(XDatSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type row_missing(row_missingSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type id_missing(id_missingSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(BISN_missing(XDat, row_missing, id_missing, eta, maxIter, tol, r, s));
    return rcpp_result_gen;
END_RCPP
}
// BISN_obsv
List BISN_obsv(arma::mat XDat, double eta, int maxIter, double tol, double r, int s);
RcppExport SEXP _BISNR_BISN_obsv(SEXP XDatSEXP, SEXP etaSEXP, SEXP maxIterSEXP, SEXP tolSEXP, SEXP rSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XDat(XDatSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(BISN_obsv(XDat, eta, maxIter, tol, r, s));
    return rcpp_result_gen;
END_RCPP
}
// QUICParameterLearning
arma::mat QUICParameterLearning(arma::mat K0, arma::mat S, arma::uvec idr, arma::uvec idc, int max_outer_iter, int max_inner_iter);
RcppExport SEXP _BISNR_QUICParameterLearning(SEXP K0SEXP, SEXP SSEXP, SEXP idrSEXP, SEXP idcSEXP, SEXP max_outer_iterSEXP, SEXP max_inner_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type K0(K0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idr(idrSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idc(idcSEXP);
    Rcpp::traits::input_parameter< int >::type max_outer_iter(max_outer_iterSEXP);
    Rcpp::traits::input_parameter< int >::type max_inner_iter(max_inner_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(QUICParameterLearning(K0, S, idr, idc, max_outer_iter, max_inner_iter));
    return rcpp_result_gen;
END_RCPP
}
