# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BISN_missing <- function(XDat, row_missing, id_missing, eta, maxIter, tol, r, s) {
    .Call(`_BISNR_BISN_missing`, XDat, row_missing, id_missing, eta, maxIter, tol, r, s)
}

BISN_obsv <- function(XDat, eta, maxIter, tol, r, s) {
    .Call(`_BISNR_BISN_obsv`, XDat, eta, maxIter, tol, r, s)
}

QUICParameterLearning <- function(K0, S, idr, idc, max_outer_iter, max_inner_iter) {
    .Call(`_BISNR_QUICParameterLearning`, K0, S, idr, idc, max_outer_iter, max_inner_iter)
}

